### ISSUE TITLE
Restyle admonitions

### ISSUE THREAD

**Issue by yangshun** [facebookincubator/infima#55] opened 2020-12-02 09:17 UTC
Refer to original issue - https://github.com/facebook/docusaurus/issues/2930 (I'm unable to move issues across organizations).

**Comment by alexkrolick** [comment] 2020-12-22 01:33
I'll just add that the current styling in facebook/docusaurus#2930 fails contrast ration checks quite badly, so it would be nice to come up with an alternative. See check below - Bootstrap's Alert panel (top) has a ration of 7.2, while the Docusaurus panels are in the 1.1-1.7 range. WCAG AA is 4.5 and AAA is 7. https://contrastchecker.com/?c=ffffff&b=ffba00

<img width="923" alt="Screen Shot 2020-12-21 at 5 18 41 PM" src="https://user-images.githubusercontent.com/1571667/102838049-0d38d480-43b2-11eb-8247-03ebf6a28ed2.png">

**Comment by slorber** [comment] 2020-12-29 14:33
We'll also have to ensure these issues get fixed by the redesign:
- https://github.com/facebook/docusaurus/issues/3923
- https://github.com/facebook/docusaurus/issues/2609

**Comment by Steviebaa** [comment] 2021-01-04 04:19
Regarding [docusaurus/issues/2930](https://github.com/facebook/docusaurus/issues/2930). Could there be an option similar to [Material-UI variant prop for elements](material ui button link). I.e if you chose `contained` you would get the original design or provide `outlined` or something along those lines to get the proposed style in the above issue. I kind of like both styles.

Looking forward to this one. Only thing holding me back from a release. Thanks!

**Comment by alexkrolick** [comment] 2021-01-05 19:58
Even if you want to create a variant with brighter backgrounds, the text color should have high contrast against it. In most cases the original background colors would need black text for that to be the case.

**Comment by HonkingGoose** [comment] 2021-01-25 22:01
## Introduction

> I'll just add that the current styling in facebook/docusaurus#2930 fails contrast ratio checks quite badly, so it would be nice to come up with an alternative.

The colored background also gets too much visual weight.

> Even if you want to create a variant with brighter backgrounds, the text color should have high contrast against it. In most cases the original background colors would need black text for that to be the case.

We don't need to use black/gray text to get accessible contrast. 😉 
The trick is to put dark colored text on a soft colored background.

Steve Schoger's advice

> Achieving an accessible contrast ratio is very difficult when using white text on a colored background.
> Using dark colored text on a soft colored background is much easier to make accessible, and usually looks better to boot

Source for quote: https://twitter.com/steveschoger/status/1045371124274483200

## Mock-up

![Admonitions - Copy](https://user-images.githubusercontent.com/34918129/105762692-0115d900-5f55-11eb-8526-bda8f1fdae75.png)

## Contrast score

The mock-up should score a AAA rating on the WCAG contrast checker.

## Steps to reproduce

1. Go to https://tailwindcss.com/docs/customizing-colors#color-palette-reference for the used colors.
2. Use color.name 50 for background.
3. Use color.name 900 for text and icon.
4. Grab icons from https://heroicons.com/ (I'm using the "outline" set.)

## De-emphasize icons

I also recommend de-emphasizing the icons by using a lighter color. Say color-name 600/500 or lighter from the TailwindCSS colors. This is **not shown** in the mock-up, as the current Docusaurus admonition design puts equal weight on the icon and the text.

If you'd like, I can make a second mock-up which does de-emphasize the icons.

## Conclusion

I hope you like my idea. 😄

**Comment by HonkingGoose** [comment] 2021-02-05 11:33
Do you want a new mockup from me based on the Infima color scheme? It might be good to see if we could use the current colors to make a better admonition design?

Does the Infima project have something like the [TailwindCSS Color palette reference](https://tailwindcss.com/docs/customizing-colors#color-palette-reference) that I can use to grab the colors from?

Also do you want a Dark Mode mockup from me?

**Comment by alexkrolick** [comment] 2021-02-05 19:41
Speaking as someone downstream of this issue, it would be nice to see some movement on the code side of things. Can definitely iterate on the details later once the immediate acccessibility issue is resolved.

I see they have a palette here: https://facebookincubator.github.io/infima/docs/utilities/colors

**Comment by HonkingGoose** [comment] 2021-02-07 17:59
## Test: lightest Infima bg color, darkest color text

I tried to replicate the mock-up that I made based off the TailwindCSS color scheme.

I used the lightest Infima color for the background and a really dark Infima color for the text.
The text looks really washed out, and we're not really gaining any contrast here.
I also could not get a nice look for the icons with the current color scheme unfortunately.

Conclusion: I think we can reject this idea, if we're not willing to add lighter shades of the Infima colors to the palette.

![Infima color admonitions](https://user-images.githubusercontent.com/34918129/107154666-85fceb80-6974-11eb-8bb6-36a0846672b2.png)

## Option 1:

This uses the Infima colors.
It also has a accent border on the left of the container for the admonition.
The title of the admonition is a plain dark grey/black.

![Infima color admonitions – Title not colored](https://user-images.githubusercontent.com/34918129/107154682-9dd46f80-6974-11eb-92a5-e4961d81685e.png)

## Option 2 (title of admonition colored):

This uses the Infima colors.
The title of the admonition is colored to stand out a bit more.
I'm not 100% on this, as some colored text still doesn't look very nice on the gray background, but this was the best I could make out of what we have now.

![Infima color admonitions Title colored](https://user-images.githubusercontent.com/34918129/107154690-adec4f00-6974-11eb-9430-507eb5359191.png)

### Variant of option 2 for darkmode

This uses the Infima colors.
The title of the admonition is colored to stand out a bit more.
There should be few colored things on a normal Darkmode view, so the accent colors really pop out here.
I'm using a off-white color for the text instead of a full white color, this is to reduce eyestrain when reading the text.
It also prevents the text from vibrating visually.

![Infima color admonitions – Title colored Darkmode](https://user-images.githubusercontent.com/34918129/107154721-d8d6a300-6974-11eb-9699-600ea394a2cf.png)

**Comment by yangshun** [comment] 2021-02-08 04:26
Thanks for the designs! I'll discuss them with designers and we should have something out by the end of this week.

**Comment by HonkingGoose** [comment] 2021-02-09 15:45
@yangshun I think we should also constrain the admonition length, see how it cover the full width of the container.

See how the admonition gets really really large in PR https://github.com/facebookincubator/infima/pull/62 if you expand the container width even more.

**Comment by yangshun** [comment] 2021-02-09 15:58
> I think we should also constrain the admonition length.

Hmm I might not agree with that. Components typically shouldn't have their lengths restricted. It should be up to the parent container to set a max width for the children to fill fully. This is better done in userland than in the framework.

**Comment by HonkingGoose** [comment] 2021-02-09 16:05
> Hmm I might not agree with that. Components typically shouldn't have their lengths restricted.

Oh okay. Just wanted to mention this problem. 😄 

>  It should be up to the parent container to set a max width for the children to fill fully. This is better done in userland than in the framework.

What does userland mean? Does that mean that I should fix this myself (I'm using the default Docusaurus v2 theme for docs pages).

Or does this mean that I should open a issue at Docusaurus v2 repo to discuss this?

**Comment by yangshun** [comment] 2021-02-09 16:24
In this case, userland would be Docusaurus repo. I agree we should restrict the land, but it should be done by the user, which is Docusaurus in this case.

**Comment by HonkingGoose** [comment] 2021-02-09 16:40
I've opened a issue at Docusaurus v2 to discuss this change in the "proper" place. Thanks for your feedback @yangshun. 😄

**Comment by yangshun** [comment] 2021-02-09 16:44
Thank you for the idea and designs!

**Comment by HonkingGoose** [comment] 2021-02-09 16:48
> 
> 
> Thank you for the idea and designs!

Thank you for the thanks! 😄 🎉 

I hope you find the ideas and designs useful. I **really** want better admonitions because the current ones do not look nice on my docs website, it's my number one thing that I want to see changed in Docusaurus.

Also, if I get this fixed upstream, I don't have to figure out the CSS to patch over the Docusaurus admonitions myself, and I also don't risk breaking stuff that Docusaurus depends on. 😄

**Comment by slorber** [comment] 2021-05-04 14:42
Another edge case admonitions redesign should take into account:

![image](https://user-images.githubusercontent.com/749374/117021433-a3cdb880-acf7-11eb-953a-18c0c9563de2.png)

**Comment by sw-yx** [comment] 2021-06-02 09:47
hi folks, am new here. whats the status of these and is there an active PR we can track/test?

**Comment by slorber** [comment] 2021-06-03 16:36
Hi

After discussions with @yangshun I think we are going to move on and implement something asap.

There are so many possible designs and it's not easy to make a choice.

My idea is to not be too disruptive for our users, particularly those that have already customized their admonitions, so we should try to avoid changing the markup too much, maybe just change the styling/CSS.

I think a good way to not be too disruptive is to actually look at custom admonitions that have been built by the community (generally, only using css and keeping existing markup), and choose/steal the best implementation.

Personally, I think what @markerikson implemented here is a good candidate:

- https://react-redux.js.org/tutorials/quick-start
- https://github.com/reduxjs/react-redux/blob/master/website/static/css/custom.css

![image](https://user-images.githubusercontent.com/749374/120680033-246c0a00-c49a-11eb-9d60-3e3ad4d70d08.png)

What do you think about it? 

If you know any other Docusaurus site that has a good customized admonition design, please report it here.

**Comment by sw-yx** [comment] 2021-06-03 16:42
oh thats pretty! me likey.

**Comment by markerikson** [comment] 2021-06-03 16:46
Yeah, I swiped the colors from Cypress's docs at https://cypress.io:

![image](https://user-images.githubusercontent.com/1128784/120681700-a4c64700-c469-11eb-9459-ed7498132c8b.png)


I've currently got it configured to keep the same colors even in dark mode, but lemme know if anyone has better ideas:

![image](https://user-images.githubusercontent.com/1128784/120681600-89f3d280-c469-11eb-87a2-12e45e8e6efb.png)

**Comment by sw-yx** [comment] 2021-06-03 17:05
i like that (keeping colors in dark mode), thats what i did on my end too. seems easiest to not screw up the internal color contrasts.

**Comment by HonkingGoose** [comment] 2021-06-03 17:15
> I think a good way to not be too disruptive is to actually look at custom admonitions that have been built by the community (generally, only using css and keeping existing markup), and choose/steal the best implementation.

That's a valid point. And stealing good designs from other is also a good way to get a battle-tested scheme. 😄 

> I've currently got it configured to keep the same colors even in dark mode, but lemme know if anyone has better ideas:

I like it, it works well on light and dark mode, it's distinct, but doesn't distract/clash with other content/sidebar.

**Comment by slorber** [comment] 2021-06-03 17:19
Also found the implementation of @iaincollins on NextAuth (including a dark mode)

- https://next-auth.js.org/getting-started/typescript
- https://github.com/nextauthjs/next-auth/blob/main/www/src/css/admonitions.css

![image](https://user-images.githubusercontent.com/749374/120685257-f25da680-c49f-11eb-85d4-020ca7535dcd.png)

Design is quite close to the one of React-Redux, just without border (like the Cypress doc it seems btw).

---

I think the presented designs are quite generic, can keep the existing markup and are not too opinionated to please a majority of users

Should we add colored border? 

Is dark mode required? (react-redux does not have dark mode but it does not look bad either)

---

Found some other sites with custom admonitions, but maybe a bit too opinionated:
- https://agile-ts.org/docs/quick-start/angular
- https://vector.dev/docs/reference/configuration/sources/apache_metrics/

---

**Comment by darekkay** [comment] 2021-06-03 20:27
One thing to keep in mind is to ensure accessible color contrasts. This can be especially tricky with nested links, e.g. blue links on blue (info) boxes. The Cypress color combinations are highly inaccessible, e.g. a `2.29` ratio for the "success" box:

![image](https://user-images.githubusercontent.com/3101914/120707180-4bd2cf00-c4ba-11eb-8a2a-20e8b91d262c.png)

> Design is quite close to the one of React-Redux, just without border (like the Cypress doc it seems btw).

I've been using such border-less alerts, but I just applied the bordered style and I actually like it more. Border-less designs are popular, but alert boxes are meant to pop out, which borders solve nicely.

**Comment by alexkrolick** [comment] 2021-06-03 21:36
> One thing to keep in mind is to ensure accessible color contrasts. This can be especially tricky with nested links, e.g. blue links on blue (info) boxes. The Cypress color combinations are highly inaccessible, e.g. a 2.29 ratio for the "success" box:

Yes, the whole reason this issue exists is because of color contrast. Let's not switch one inaccessible palette for another.

**Comment by slorber** [comment] 2021-07-20 09:58
Here's a first version of a redesign proposal:

![image](https://user-images.githubusercontent.com/749374/126302746-f116f9fc-fd39-4e91-905e-1c5d261f1f98.png)

PR with more infos here: https://github.com/facebookincubator/infima/pull/155

It has light/dark mode support and colors are easy to customize

I did not apply a border by default, but added some light shado, and you can add a 1px border easily with a single CSS env variable.

Regarding WCAG tests:
- text pass AAA normal
- code block pass AA normal, some fail AAA but not too far (contrast > 6)
- links are unchanged and pass AAA normal

It's not so easy to make code blocks and link visible without lowering the contract, if you have ideas to improve let me know. Otherwise not passing AAA normal for all edge cases does not seem like a 100% mandatory requirement as long as contract is good enough. What do you think?

**Comment by alexkrolick** [comment] 2021-07-20 20:28
Double-checked the colors with the proposed method for checking legibility for the next WCAG version. It won't be live for a while (years) but it seems like a good idea to see if the result substantially differs from the existing AAA calculation.

It looks like most of the colors are good at 16px/400 weight, but the red & green ones are marginal (you'd want a score of 3 or above for content text).

You could increase the font-weight, font-size, or darken the text color if you want to improve the score.

Tool: https://www.myndex.com/SAPC/)

<details>

<summary>
SAPC Results (WCAG 3 Beta) 

</summary>

![Screen Shot 2021-07-20 at 10 24 48 AM](https://user-images.githubusercontent.com/1571667/126371464-33ea4b25-35b1-4b15-b0aa-e3ff96dc0224.png)
![Screen Shot 2021-07-20 at 10 25 28 AM](https://user-images.githubusercontent.com/1571667/126371471-4682abd6-1316-4660-947d-5bffceccd6bd.png)
![Screen Shot 2021-07-20 at 10 26 35 AM](https://user-images.githubusercontent.com/1571667/126371475-3bffea2d-b557-4ea0-b443-783c0661c196.png)
![Screen Shot 2021-07-20 at 10 27 14 AM](https://user-images.githubusercontent.com/1571667/126371479-5c6d5eee-8cb3-4f89-b216-1c7fd0bb938d.png)
![Screen Shot 2021-07-20 at 10 28 33 AM](https://user-images.githubusercontent.com/1571667/126371481-6b7e6c4b-0d2f-43cc-9cac-f80824d94ab6.png)


</details>

Side note - regardless of fg/bg color, it's a good idea to keep using icons to accommodate color blindness.

**Comment by slorber** [comment] 2021-07-21 09:06
Thanks @alexkrolick 

Took me some time to figure out how this works, but what I understand is that:
- I should go there: https://www.myndex.com/APCA/fullmatrix
- I should copy/paste the colors
- Cell at (score 3, 400) should display value < 16px
- Switch to check both light/dark mode (score can be different)

> Side note - regardless of fg/bg color, it's a good idea to keep using icons to accommodate color blindness.

Existing icons will be kept in Docusaurus, but they are not directly part of Infima.

---

Trying to adjust colors so that we have a min of score 3 everywhere.

---

For light mode, using a lighter background looks better to me:

![image](https://user-images.githubusercontent.com/749374/126460989-47d41516-0f1d-40f5-8ce0-970bf8745a0c.png)

Using a darker font does not work. Even black gives a score of 2:

![image](https://user-images.githubusercontent.com/749374/126462471-9a895604-a680-4cd2-bf40-6695ee86f877.png)

---

For dark mode, making the background darker looks too dark to me

![image](https://user-images.githubusercontent.com/749374/126461202-866e09cd-695f-42c4-ad0d-f3738133504b.png)

I suggest this one instead:

![image](https://user-images.githubusercontent.com/749374/126461807-97831c62-1252-4762-9fb7-ebfe7ef1369d.png)

Both can give a score of 3. 

Any opinion?

**Comment by HonkingGoose** [comment] 2021-07-21 09:28
> For light mode, using a lighter background looks better to me:
> 
> ![image](https://user-images.githubusercontent.com/749374/126460989-47d41516-0f1d-40f5-8ce0-970bf8745a0c.png)

I like it! 😄 👍

Some great design advice from Steve Schoger:

>🔥 Achieving an accessible contrast ratio is very difficult when using white text on a colored background.
>
> Using dark colored text on a soft colored background is much easier to make accessible, and usually looks better to boot 
> ![use_dark_colored_text_on_soft_colored_background](https://user-images.githubusercontent.com/34918129/126464978-6c02a62b-a34d-4ff1-abe2-9fade3dbca22.png)

Source: https://twitter.com/steveschoger/status/1045371124274483200/photo/1

---

> For dark mode, making the background darker looks too dark to me
> 
> ![image](https://user-images.githubusercontent.com/749374/126461202-866e09cd-695f-42c4-ad0d-f3738133504b.png)

This one is too dark, and it doesn't stand out enough anymore, because the colors are so dim.
I'd say we reject this one.

> I suggest this one instead:
> 
> ![image](https://user-images.githubusercontent.com/749374/126461807-97831c62-1252-4762-9fb7-ebfe7ef1369d.png)

I this one best out of the 3 dark mode designs!

**Comment by alexkrolick** [comment] 2021-07-21 16:04
> - I should go there: https://www.myndex.com/APCA/fullmatrix
> - I should copy/paste the colors
> - Cell at (score 3, 400) should display value < 16px
> - Switch to check both light/dark mode (score can be different)

✅ Yes

I think both of the designs you suggested look great.

<details>

<summary>(These two)</summary>


![](https://user-images.githubusercontent.com/749374/126460989-47d41516-0f1d-40f5-8ce0-970bf8745a0c.png)

![](https://user-images.githubusercontent.com/749374/126461807-97831c62-1252-4762-9fb7-ebfe7ef1369d.png)

</details>

**Closed** 2021-07-23 14:14 UTC
